// Bingo content bank — read by BingoGame.
// answer is what prints on the cell; exampleSentence is the definition cue
// (the answer word appears in it EXACTLY once, in the same form as `answer`,
// never inside another word — the game blanks it with a literal replace).
import type { GameItem } from "@/lib/game-contract";

export const BINGO_KITCHEN: GameItem[] = [
  { id: "ki-1", prompt: "kettle", answer: "kettle", cefr: "A1", exampleSentence: "Put the kettle on if you want some tea." },
  { id: "ki-2", prompt: "fridge", answer: "fridge", cefr: "A1", exampleSentence: "The milk is in the fridge so it stays cold." },
  { id: "ki-3", prompt: "fork", answer: "fork", cefr: "A1", exampleSentence: "We eat salad with a knife and fork." },
  { id: "ki-4", prompt: "spoon", answer: "spoon", cefr: "A1", exampleSentence: "You eat soup with a spoon." },
  { id: "ki-5", prompt: "plate", answer: "plate", cefr: "A1", exampleSentence: "Put the pizza on a big plate." },
  { id: "ki-6", prompt: "cup", answer: "cup", cefr: "A1", exampleSentence: "There's a cup of coffee on the desk." },
  { id: "ki-7", prompt: "knife", answer: "knife", cefr: "A1", exampleSentence: "Be careful, that knife is very sharp." },
  { id: "ki-8", prompt: "bowl", answer: "bowl", cefr: "A1", exampleSentence: "There's some rice left in the bowl." },
  { id: "ki-9", prompt: "oven", answer: "oven", cefr: "A1", exampleSentence: "The bread has just come out of the oven, so it's hot." },
  { id: "ki-10", prompt: "sink", answer: "sink", cefr: "A1", exampleSentence: "Wash your hands in the sink before dinner." },
  { id: "ki-11", prompt: "tap", answer: "tap", cefr: "A1", exampleSentence: "Turn off the tap when you finish washing." },
  { id: "ki-12", prompt: "toaster", answer: "toaster", cefr: "A1", exampleSentence: "The toaster is broken, so we can't have toast." },
  { id: "ki-13", prompt: "pot", answer: "pot", cefr: "A1", exampleSentence: "The soup is cooking in a big pot on the stove." },
  { id: "ki-14", prompt: "mug", answer: "mug", cefr: "A1", exampleSentence: "He drinks hot chocolate from a blue mug." },
  { id: "ki-15", prompt: "cupboard", answer: "cupboard", cefr: "A1", exampleSentence: "The glasses are in the cupboard above the sink." },
  { id: "ki-16", prompt: "microwave", answer: "microwave", cefr: "A1", exampleSentence: "Heat the soup in the microwave for two minutes." },
];

export const BINGO_CLOTHES: GameItem[] = [
  { id: "cl-1", prompt: "shirt", answer: "shirt", cefr: "A1", exampleSentence: "He wears a clean shirt to work every day." },
  { id: "cl-2", prompt: "jacket", answer: "jacket", cefr: "A1", exampleSentence: "It's cold outside, so put on your jacket." },
  { id: "cl-3", prompt: "shoes", answer: "shoes", cefr: "A1", exampleSentence: "Take off your shoes before you come in." },
  { id: "cl-4", prompt: "dress", answer: "dress", cefr: "A1", exampleSentence: "She wore a red dress to the party." },
  { id: "cl-5", prompt: "trousers", answer: "trousers", cefr: "A1", exampleSentence: "These trousers are too long for me." },
  { id: "cl-6", prompt: "coat", answer: "coat", cefr: "A1", exampleSentence: "You'll need a warm coat in the winter." },
  { id: "cl-7", prompt: "hat", answer: "hat", cefr: "A1", exampleSentence: "He wears a hat when the sun is strong." },
  { id: "cl-8", prompt: "socks", answer: "socks", cefr: "A1", exampleSentence: "I can't find my black socks anywhere." },
  { id: "cl-9", prompt: "skirt", answer: "skirt", cefr: "A1", exampleSentence: "Her skirt is blue with white flowers." },
  { id: "cl-10", prompt: "sweater", answer: "sweater", cefr: "A1", exampleSentence: "This sweater is made of wool, so it's very warm." },
  { id: "cl-11", prompt: "jeans", answer: "jeans", cefr: "A1", exampleSentence: "I usually wear jeans and a T-shirt at the weekend." },
  { id: "cl-12", prompt: "boots", answer: "boots", cefr: "A1", exampleSentence: "Wear your boots — it's raining outside." },
  { id: "cl-13", prompt: "gloves", answer: "gloves", cefr: "A1", exampleSentence: "My hands are cold, so I'll wear my gloves." },
  { id: "cl-14", prompt: "scarf", answer: "scarf", cefr: "A1", exampleSentence: "She wears a scarf around her neck when it's cold." },
  { id: "cl-15", prompt: "tie", answer: "tie", cefr: "A1", exampleSentence: "He has to wear a tie at school." },
  { id: "cl-16", prompt: "belt", answer: "belt", cefr: "A1", exampleSentence: "These pants are too big, so I need a belt." },
];

export const BINGO_BODY: GameItem[] = [
  { id: "bd-1", prompt: "head", answer: "head", cefr: "A1", exampleSentence: "He hit his head on the door and it really hurts." },
  { id: "bd-2", prompt: "hand", answer: "hand", cefr: "A1", exampleSentence: "She held the cup carefully in one hand." },
  { id: "bd-3", prompt: "foot", answer: "foot", cefr: "A1", exampleSentence: "I hurt my foot playing soccer yesterday." },
  { id: "bd-4", prompt: "leg", answer: "leg", cefr: "A1", exampleSentence: "He broke his leg when he fell off his bike." },
  { id: "bd-5", prompt: "arm", answer: "arm", cefr: "A1", exampleSentence: "She carries her little boy on her arm." },
  { id: "bd-6", prompt: "eye", answer: "eye", cefr: "A1", exampleSentence: "There's something in my eye and I can't see well." },
  { id: "bd-7", prompt: "ear", answer: "ear", cefr: "A1", exampleSentence: "He whispered something in her ear." },
  { id: "bd-8", prompt: "nose", answer: "nose", cefr: "A1", exampleSentence: "My nose runs when I have a cold." },
  { id: "bd-9", prompt: "mouth", answer: "mouth", cefr: "A1", exampleSentence: "Don't talk with your mouth full." },
  { id: "bd-10", prompt: "tooth", answer: "tooth", cefr: "A1", exampleSentence: "My tooth hurts, so I need to see the dentist." },
  { id: "bd-11", prompt: "hair", answer: "hair", cefr: "A1", exampleSentence: "She has long black hair." },
  { id: "bd-12", prompt: "finger", answer: "finger", cefr: "A1", exampleSentence: "He cut his finger while he was cooking." },
  { id: "bd-13", prompt: "neck", answer: "neck", cefr: "A1", exampleSentence: "A giraffe has a very long neck." },
  { id: "bd-14", prompt: "shoulder", answer: "shoulder", cefr: "A1", exampleSentence: "He carried the heavy bag on his shoulder." },
  { id: "bd-15", prompt: "knee", answer: "knee", cefr: "A1", exampleSentence: "I fell on the playground and hurt my knee." },
  { id: "bd-16", prompt: "back", answer: "back", cefr: "A1", exampleSentence: "My back hurts from sitting all day." },
];

export const BINGO_WEATHER: GameItem[] = [
  { id: "we-1", prompt: "rain", answer: "rain", cefr: "A1", exampleSentence: "Take an umbrella, because it looks like rain." },
  { id: "we-2", prompt: "snow", answer: "snow", cefr: "A1", exampleSentence: "The children are playing in the snow." },
  { id: "we-3", prompt: "wind", answer: "wind", cefr: "A1", exampleSentence: "The wind is so strong that it's hard to walk." },
  { id: "we-4", prompt: "sun", answer: "sun", cefr: "A1", exampleSentence: "The sun is very hot today, so drink lots of water." },
  { id: "we-5", prompt: "cloud", answer: "cloud", cefr: "A1", exampleSentence: "There's not a cloud in the sky this morning." },
  { id: "we-6", prompt: "storm", answer: "storm", cefr: "A1", exampleSentence: "The storm knocked down some trees last night." },
  { id: "we-7", prompt: "fog", answer: "fog", cefr: "A1", exampleSentence: "Drive slowly — you can't see the road in the fog." },
  { id: "we-8", prompt: "ice", answer: "ice", cefr: "A1", exampleSentence: "Be careful, there's ice on the road this morning." },
  { id: "we-9", prompt: "rainbow", answer: "rainbow", cefr: "A1", exampleSentence: "After the rain, we saw a beautiful rainbow." },
  { id: "we-10", prompt: "lightning", answer: "lightning", cefr: "A1", exampleSentence: "The lightning lit up the whole sky." },
  { id: "we-11", prompt: "thunder", answer: "thunder", cefr: "A1", exampleSentence: "The thunder was so loud it woke the baby." },
  { id: "we-12", prompt: "frost", answer: "frost", cefr: "A1", exampleSentence: "There was frost on the car this morning." },
  { id: "we-13", prompt: "hail", answer: "hail", cefr: "A1", exampleSentence: "The hail was so big it broke a window." },
  { id: "we-14", prompt: "breeze", answer: "breeze", cefr: "A2", exampleSentence: "A cool breeze is coming from the sea." },
  { id: "we-15", prompt: "sunshine", answer: "sunshine", cefr: "A1", exampleSentence: "Let's sit in the sunshine and eat our lunch." },
  { id: "we-16", prompt: "shower", answer: "shower", cefr: "A2", exampleSentence: "There will be a light shower this afternoon." },
];

export const BINGO_ANIMALS: GameItem[] = [
  { id: "an-1", prompt: "dog", answer: "dog", cefr: "A1", exampleSentence: "The dog waits by the door for its walk." },
  { id: "an-2", prompt: "cat", answer: "cat", cefr: "A1", exampleSentence: "The cat is sleeping on the sofa." },
  { id: "an-3", prompt: "horse", answer: "horse", cefr: "A1", exampleSentence: "She rides a horse every weekend." },
  { id: "an-4", prompt: "cow", answer: "cow", cefr: "A1", exampleSentence: "The cow gives us milk." },
  { id: "an-5", prompt: "sheep", answer: "sheep", cefr: "A1", exampleSentence: "We get wool from a sheep." },
  { id: "an-6", prompt: "chicken", answer: "chicken", cefr: "A1", exampleSentence: "The chicken laid an egg this morning." },
  { id: "an-7", prompt: "duck", answer: "duck", cefr: "A1", exampleSentence: "The duck is swimming on the lake." },
  { id: "an-8", prompt: "rabbit", answer: "rabbit", cefr: "A1", exampleSentence: "A rabbit has long ears and eats carrots." },
  { id: "an-9", prompt: "mouse", answer: "mouse", cefr: "A1", exampleSentence: "A mouse ran under the fridge last night." },
  { id: "an-10", prompt: "snake", answer: "snake", cefr: "A1", exampleSentence: "A snake has no legs." },
  { id: "an-11", prompt: "bird", answer: "bird", cefr: "A1", exampleSentence: "A bird is singing in the tree outside." },
  { id: "an-12", prompt: "fish", answer: "fish", cefr: "A1", exampleSentence: "A fish can't live out of water." },
  { id: "an-13", prompt: "elephant", answer: "elephant", cefr: "A1", exampleSentence: "An elephant is the biggest animal on land." },
  { id: "an-14", prompt: "tiger", answer: "tiger", cefr: "A1", exampleSentence: "A tiger has black and orange stripes." },
  { id: "an-15", prompt: "monkey", answer: "monkey", cefr: "A1", exampleSentence: "The monkey is eating a banana in the tree." },
  { id: "an-16", prompt: "frog", answer: "frog", cefr: "A1", exampleSentence: "A frog can jump a very long way." },
];

export const BINGO_TOWN: GameItem[] = [
  { id: "tw-1", prompt: "bank", answer: "bank", cefr: "A2", exampleSentence: "I need to go to the bank to get some cash." },
  { id: "tw-2", prompt: "library", answer: "library", cefr: "A2", exampleSentence: "You can borrow books for free from the library." },
  { id: "tw-3", prompt: "hospital", answer: "hospital", cefr: "A2", exampleSentence: "The ambulance took him straight to the hospital." },
  { id: "tw-4", prompt: "pharmacy", answer: "pharmacy", cefr: "A2", exampleSentence: "You can buy medicine at the pharmacy." },
  { id: "tw-5", prompt: "supermarket", answer: "supermarket", cefr: "A2", exampleSentence: "We buy all our food at the supermarket." },
  { id: "tw-6", prompt: "post office", answer: "post office", cefr: "A2", exampleSentence: "You can send a package from the post office." },
  { id: "tw-7", prompt: "bridge", answer: "bridge", cefr: "A2", exampleSentence: "The bridge crosses the river in the middle of town." },
  { id: "tw-8", prompt: "station", answer: "station", cefr: "A2", exampleSentence: "The train leaves the station at nine o'clock." },
  { id: "tw-9", prompt: "museum", answer: "museum", cefr: "A2", exampleSentence: "You can see old paintings in the museum." },
  { id: "tw-10", prompt: "playground", answer: "playground", cefr: "A2", exampleSentence: "The children are on the swings in the playground." },
  { id: "tw-11", prompt: "bakery", answer: "bakery", cefr: "A2", exampleSentence: "The bakery sells fresh bread every morning." },
  { id: "tw-12", prompt: "gym", answer: "gym", cefr: "A2", exampleSentence: "She goes to the gym three times a week to exercise." },
  { id: "tw-13", prompt: "hotel", answer: "hotel", cefr: "A2", exampleSentence: "They stayed in a small hotel near the beach." },
  { id: "tw-14", prompt: "parking lot", answer: "parking lot", cefr: "A2", exampleSentence: "Leave the car in the parking lot behind the store." },
  { id: "tw-15", prompt: "crosswalk", answer: "crosswalk", cefr: "A2", exampleSentence: "Always cross the road at the crosswalk." },
  { id: "tw-16", prompt: "fountain", answer: "fountain", cefr: "A2", exampleSentence: "There's a beautiful fountain in the middle of the square." },
];

export const BINGO_JOBS: GameItem[] = [
  { id: "jb-1", prompt: "teacher", answer: "teacher", cefr: "A2", exampleSentence: "A teacher helps students learn new things." },
  { id: "jb-2", prompt: "doctor", answer: "doctor", cefr: "A2", exampleSentence: "You see a doctor when you are sick." },
  { id: "jb-3", prompt: "nurse", answer: "nurse", cefr: "A2", exampleSentence: "A nurse helps sick people in a hospital." },
  { id: "jb-4", prompt: "police officer", answer: "police officer", cefr: "A2", exampleSentence: "Call a police officer if someone steals your car." },
  { id: "jb-5", prompt: "firefighter", answer: "firefighter", cefr: "A2", exampleSentence: "A firefighter puts out fires and saves people." },
  { id: "jb-6", prompt: "dentist", answer: "dentist", cefr: "A2", exampleSentence: "A dentist looks after your teeth." },
  { id: "jb-7", prompt: "chef", answer: "chef", cefr: "A2", exampleSentence: "The chef cooks all the food in the restaurant." },
  { id: "jb-8", prompt: "waiter", answer: "waiter", cefr: "A2", exampleSentence: "The waiter brought us the menu and some water." },
  { id: "jb-9", prompt: "driver", answer: "driver", cefr: "A2", exampleSentence: "The bus driver stops at every corner." },
  { id: "jb-10", prompt: "farmer", answer: "farmer", cefr: "A2", exampleSentence: "A farmer grows vegetables and keeps animals." },
  { id: "jb-11", prompt: "vet", answer: "vet", cefr: "A2", exampleSentence: "We took our sick dog to the vet." },
  { id: "jb-12", prompt: "pilot", answer: "pilot", cefr: "A2", exampleSentence: "A pilot flies a plane." },
  { id: "jb-13", prompt: "singer", answer: "singer", cefr: "A2", exampleSentence: "The singer has a beautiful voice." },
  { id: "jb-14", prompt: "actor", answer: "actor", cefr: "A2", exampleSentence: "The actor plays a doctor in the show." },
  { id: "jb-15", prompt: "engineer", answer: "engineer", cefr: "A2", exampleSentence: "An engineer designed the new bridge." },
  { id: "jb-16", prompt: "mechanic", answer: "mechanic", cefr: "A2", exampleSentence: "The mechanic is fixing our car this week." },
];

export const BINGO_TRANSPORT: GameItem[] = [
  { id: "tr-1", prompt: "bus", answer: "bus", cefr: "A2", exampleSentence: "The bus stops right outside my house." },
  { id: "tr-2", prompt: "train", answer: "train", cefr: "A2", exampleSentence: "The train to Chicago leaves at eight." },
  { id: "tr-3", prompt: "plane", answer: "plane", cefr: "A2", exampleSentence: "The plane is flying high above the clouds." },
  { id: "tr-4", prompt: "bike", answer: "bike", cefr: "A2", exampleSentence: "He rides his bike to school every day." },
  { id: "tr-5", prompt: "boat", answer: "boat", cefr: "A2", exampleSentence: "We crossed the lake in a small boat." },
  { id: "tr-6", prompt: "taxi", answer: "taxi", cefr: "A2", exampleSentence: "Let's take a taxi to the airport." },
  { id: "tr-7", prompt: "subway", answer: "subway", cefr: "A2", exampleSentence: "The subway is the fastest way across the city." },
  { id: "tr-8", prompt: "ferry", answer: "ferry", cefr: "A2", exampleSentence: "The ferry takes people and cars across the river." },
  { id: "tr-9", prompt: "helicopter", answer: "helicopter", cefr: "A2", exampleSentence: "A helicopter landed on the hospital roof." },
  { id: "tr-10", prompt: "truck", answer: "truck", cefr: "A2", exampleSentence: "The truck is carrying boxes to the store." },
  { id: "tr-11", prompt: "scooter", answer: "scooter", cefr: "A2", exampleSentence: "She goes to work on her little scooter." },
  { id: "tr-12", prompt: "car", answer: "car", cefr: "A2", exampleSentence: "My car is parked outside the house." },
  { id: "tr-13", prompt: "ship", answer: "ship", cefr: "A2", exampleSentence: "The ship is carrying new cars from Japan." },
  { id: "tr-14", prompt: "motorcycle", answer: "motorcycle", cefr: "A2", exampleSentence: "He always wears a helmet on his motorcycle." },
  { id: "tr-15", prompt: "ambulance", answer: "ambulance", cefr: "A2", exampleSentence: "The ambulance took her to the hospital quickly." },
  { id: "tr-16", prompt: "spaceship", answer: "spaceship", cefr: "A2", exampleSentence: "The spaceship is flying all the way to the moon." },
];

export const BINGO_FEELINGS: GameItem[] = [
  { id: "fe-1", prompt: "happy", answer: "happy", cefr: "A2", exampleSentence: "She was happy because she passed the test." },
  { id: "fe-2", prompt: "sad", answer: "sad", cefr: "A2", exampleSentence: "He felt sad when his team lost the game." },
  { id: "fe-3", prompt: "angry", answer: "angry", cefr: "A2", exampleSentence: "She was angry because someone broke her phone." },
  { id: "fe-4", prompt: "tired", answer: "tired", cefr: "A2", exampleSentence: "I'm tired because I went to bed very late." },
  { id: "fe-5", prompt: "bored", answer: "bored", cefr: "A2", exampleSentence: "The children were bored during the long car ride." },
  { id: "fe-6", prompt: "scared", answer: "scared", cefr: "A2", exampleSentence: "He is scared of spiders." },
  { id: "fe-7", prompt: "worried", answer: "worried", cefr: "A2", exampleSentence: "She is worried about her exam tomorrow." },
  { id: "fe-8", prompt: "excited", answer: "excited", cefr: "A2", exampleSentence: "The kids are excited about the school trip." },
  { id: "fe-9", prompt: "surprised", answer: "surprised", cefr: "A2", exampleSentence: "I was so surprised when everyone shouted 'Happy Birthday'." },
  { id: "fe-10", prompt: "nervous", answer: "nervous", cefr: "A2", exampleSentence: "He felt nervous before the big interview." },
  { id: "fe-11", prompt: "proud", answer: "proud", cefr: "A2", exampleSentence: "Her parents were proud when she won the race." },
  { id: "fe-12", prompt: "lonely", answer: "lonely", cefr: "A2", exampleSentence: "He felt lonely in the new city with no friends." },
  { id: "fe-13", prompt: "embarrassed", answer: "embarrassed", cefr: "A2", exampleSentence: "She felt embarrassed when she dropped her tray in the cafeteria." },
  { id: "fe-14", prompt: "relaxed", answer: "relaxed", cefr: "A2", exampleSentence: "I feel relaxed when I listen to quiet music." },
  { id: "fe-15", prompt: "disappointed", answer: "disappointed", cefr: "A2", exampleSentence: "They were disappointed when the game was cancelled." },
  { id: "fe-16", prompt: "confused", answer: "confused", cefr: "A2", exampleSentence: "The students looked confused by the strange question." },
];

export const BINGO_WORKPLACE: GameItem[] = [
  { id: "wk-1", prompt: "deadline", answer: "deadline", cefr: "B1", exampleSentence: "We have to finish the report before the deadline on Friday." },
  { id: "wk-2", prompt: "meeting", answer: "meeting", cefr: "B1", exampleSentence: "The meeting starts at ten, so don't be late." },
  { id: "wk-3", prompt: "interview", answer: "interview", cefr: "B1", exampleSentence: "She has a job interview tomorrow morning." },
  { id: "wk-4", prompt: "salary", answer: "salary", cefr: "B1", exampleSentence: "He gets his salary at the end of every month." },
  { id: "wk-5", prompt: "promotion", answer: "promotion", cefr: "B1", exampleSentence: "She got a promotion and now manages a small team." },
  { id: "wk-6", prompt: "colleague", answer: "colleague", cefr: "B1", exampleSentence: "My colleague sits at the desk next to mine." },
  { id: "wk-7", prompt: "manager", answer: "manager", cefr: "B1", exampleSentence: "If there's a problem, speak to the manager." },
  { id: "wk-8", prompt: "break room", answer: "break room", cefr: "B1", exampleSentence: "There's free coffee in the break room on the second floor." },
  { id: "wk-9", prompt: "schedule", answer: "schedule", cefr: "B1", exampleSentence: "The new work schedule starts on Monday." },
  { id: "wk-10", prompt: "invoice", answer: "invoice", cefr: "B1", exampleSentence: "The company sent us an invoice for the work." },
  { id: "wk-11", prompt: "training", answer: "training", cefr: "B1", exampleSentence: "All new employees get two weeks of training." },
  { id: "wk-12", prompt: "contract", answer: "contract", cefr: "B1", exampleSentence: "Read the contract carefully before you sign it." },
  { id: "wk-13", prompt: "resignation", answer: "resignation", cefr: "B1", exampleSentence: "He sent his resignation by email on Friday." },
  { id: "wk-14", prompt: "overtime", answer: "overtime", cefr: "B1", exampleSentence: "She worked overtime all week to finish the project." },
  { id: "wk-15", prompt: "shift", answer: "shift", cefr: "B1", exampleSentence: "My shift starts at six in the morning." },
  { id: "wk-16", prompt: "headquarters", answer: "headquarters", cefr: "B1", exampleSentence: "The company's headquarters is in Chicago." },
];

export const ALL_BINGO: GameItem[] = [
  ...BINGO_KITCHEN,
  ...BINGO_CLOTHES,
  ...BINGO_BODY,
  ...BINGO_WEATHER,
  ...BINGO_ANIMALS,
  ...BINGO_TOWN,
  ...BINGO_JOBS,
  ...BINGO_TRANSPORT,
  ...BINGO_FEELINGS,
  ...BINGO_WORKPLACE,
];
